shinyServer(function(input, output) {
  
  # ---------------------------------------------------------------------------------
  # Please *name* each function beforehand using this to make the codes more readable
  # Preferably same *name* as the *separate function file*
  # ---------------------------------------------------------------------------------

  # ---------------------------------------------------------------------------------
  # Descriptions
  # ---------------------------------------------------------------------------------
  output$description_reddit <- renderUI({
   HTML("Reddit is an American social news aggregation, web content rating, and discussion website. Registered members submit content to the site such as links, text posts, and images, which are then voted up or down by other members. Posts are organized by subject into user-created boards called 'subreddits', which cover a variety of topics including news, science, movies, video games, music, books, fitness, food, and image-sharing. Submissions with more up-votes appear towards the top of their subreddit and, if they receive enough votes, ultimately on the site's front page. Despite strict rules prohibiting harassment, Reddit's administrators spend considerable resources on moderating the site."
   )})
  output$description_orlando <- renderText({
    HTML("On June 12, 2016, Omar Mateen, a 29-year-old security guard, killed 49 people and wounded 53 others in a mass shooting inside Pulse, a gay nightclub in Orlando, Florida, United States. Orlando Police Department officers shot and killed him after a three-hour standoff. 
    
In a 9-1-1 call shortly after the shooting began, Mateen swore allegiance to the leader of the Islamic State of Iraq and the Levant, Abu Bakr al-Baghdadi, and said the U.S. killing of Abu Waheeb in Iraq the previous month 'triggered' the shooting. He later told a negotiator he was 'out here right now' because of the American-led interventions in Iraq and in Syria and that the negotiator should tell the United States to stop the bombing. The incident was deemed a terrorist attack by FBI investigators.
    
Pulse was hosting a 'Latin Night', and most of the victims were Hispanic. It is the deadliest incident of violence against LGBT people in U.S. history and the deadliest terrorist attack in the U.S. since the September 11 attacks in 2001. At the time, it was the deadliest mass shooting by a single shooter in U.S. history, being surpassed by the Las Vegas shooting a year later. By June 2018, the FBI had declined to classify the incident as an anti-gay hate crime, as evidence suggested that Mateen had scouted several different targets before choosing Pulse, without knowing that it was a gay nightclub."
  )})
  output$description_ferguson <- renderText({
    HTML("The Ferguson unrest, sometimes called the Ferguson Uprising or simply Ferguson, involved protests and riots that began the day after the fatal shooting of Michael Brown by police officer Darren Wilson on August 9, 2014, in Ferguson, Missouri. The unrest sparked a vigorous debate in the United States about the relationship between law enforcement officers and African Americans, the militarization of police, and the use-of-force law in Missouri and nationwide. Continued activism expanded the issues to include modern-day debtors prisons, for-profit policing,and school segregation.

As the details of the original shooting emerged, police established curfews and deployed riot squads to maintain order. Along with peaceful protests, there was significant looting and violent unrest in the vicinity of the original shooting, as well as across the city. According to media reports, there was reactionary police militarization when dealing with violent protests in Ferguson. The unrest continued on November 24, 2014, after a grand jury did not indict Officer Wilson. It briefly continued again on the one-year anniversary of Brown's shooting. The U.S. Department of Justice concluded Wilson shot Brown in self-defense.

In response to the shooting and subsequent unrest, the U.S. Department of Justice (DOJ) conducted an investigation into the policing practices of the Ferguson Police Department (FPD). In March 2015, the DOJ announced that they had determined that the FPD had engaged in misconduct against the citizenry of Ferguson by among other things discriminating against African Americans and applying racial stereotypes, in a 'pattern or practice of unlawful conduct.' The DOJ also found that Ferguson depended on fines and other charges generated by police.
    ")
  })
  output$description_obama <- renderText({
    HTML("President Barack Obama arrived to small but cheering crowds on Sunday at the start of a historic visit to Cuba that opened a new chapter in U.S. engagement with the island's Communist government after decades of hostility between the former Cold War foes.

The three-day trip, the first by a U.S. president to Cuba in 88 years, is the culmination of a diplomatic opening announced by Obama and Cuban President Raul Castro in December 2014, ending an estrangement that began when the Cuban revolution ousted a pro-American government in 1959.    
    ")
  })
  output$description_trump <- renderText({
    HTML("On Wednesday, Time magazine announced Donald Trump as its 'Person of the Year.' On the cover, Time wrote that he'd become president of the 'divided states of America.'

While some Trump supporters greeted the announcement with joy, others noted that the editorial was highly critical of him and the type of damage he's already caused. NeverTrumpers and Clinton supporters noted that Hitler and Putin had both received the award before and that this was no honor.

At a loss for words, the social media responded with jokes, GIFs and outrage.
    ")
  })
  output$description_dataset1 <- renderText({
    HTML("The hyperlink network represents the directed, weighted connections between two subreddits (a subreddit is a community on Reddit). The network is extracted from publicly available Reddit data of 2.5 years from Jan 2014 to April 2017. The subreddit-to-subreddit hyperlink network is extracted from the posts that create hyperlinks from one subreddit to another. We say a hyperlink originates from a post in the source community and links to a post in the target community. Each hyperlink is annotated with three properties: the timestamp, the sentiment of the source community post towards the target community post, and the text property vector of the source post. The network is directed, signed, temporal, and attributed.
    ")
  })  
  output$description_dataset2 <- renderText({
    HTML("
The data consists of two sets (title lines and body texts, each >300k samples) with identical columns. Useful properties (such as sentiment and readability index) were maintained while other features were excluded in order to fulfil our value proposition. 
<br/><br/>
<strong>SOURCE_SUBREDDIT: </strong>the subreddit where the link is originated.
<br/><br/>
<strong>TARGET_SUBREDDIT: </strong>the subreddit towards which the link is directed.
<br/><br/>
<strong>POST_ID: </strong>the post in the source subreddit that starts the link
<br/><br/>
<strong>TIMESTAMP: </strong>time of the post
<br/><br/>
<strong>LINK_SENTIMENT: </strong>value indicating if the source post is explicitly negative towards the target post. The value is -1 if the source is negative towards the target, and 1 if it is neutral or positive. However, we will be using the raw VADER score in the data (positive/ negative/ compound sentiment). VADER is sentiment reasoner based on a lexicon of over 7000 manually validated features.
<br/><br/>
<strong>Automated readability index: </strong>label indicating the confidence of sentiment categorization. We might filter data with it.
We will concatenate the two datasets and use ‘POST_ID’ to match the titles to the post bodies.

         "
    )
  }) 
  # ---------------------------------------------------------------------------------
  # Example function
  # ---------------------------------------------------------------------------------
  output$distPlot <- renderPlot({
    # generate bins based on input$bins from ui.R
    x    <- faithful[, 2] 
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
    # draw the histogram with the specified number of bins
    hist(x, breaks = bins, col = 'darkgray', border = 'white')
  })
  
})#end of ShinyServer